### ISSUE TITLE
Updating iOS documentation

### ISSUE THREAD

**Issue by padcrafting** [yy502/inkscape-laserpecker#15]
Tested on iOS 16 (also iPad OS 16). 

Save gcode file on any cloud based volume accessible to the Files app. This can be on iCloud by default, although Files can be used to access other cloud storage services such as DropBox. From the Files app, copy the gcode file by long pressing the file, and selecting Copy. Navigate back to the root level of the Files app, and select the On My iPhone location. Paste the gcode file in LaserPecker/Matarialgcode folder in the On My iPhone location. The gcode file will now be available in G-code section of the Examples section in the LaserPecker app.

**Comment by yy502** [comment]
many thanks for your input
