### ISSUE TITLE
laserpecker pro - Gcode issue

### ISSUE THREAD

**Issue by Zezoh** [yy502/inkscape-laserpecker#3]
every time I start the gcode the laser start and end immediately.

**Comment by yy502** [comment]
please post a sample gcode file that's causing this issue.

**Comment by Zezoh** [comment]
Please check this : 

[Inkscape gcode.txt](https://github.com/yy502/inkscape-laserpecker/files/5434661/Inkscape.gcode.txt)

**Comment by yy502** [comment]
thanks for the sample. it works fine with my L1 and Pro. I think it's a power issue. Please try a different 5V2A phone charger for power, and/or a different USB C cable.

**Comment by Zezoh** [comment]
The sample gcode inside their app works fine :(

**Comment by yy502** [comment]
easy to check. generate a new gcode file with **a different file name**, with **power 150**, and try it out.
